.TH ignotum_strerror 3 "07 May 2016" "Library" "libignotum man page"
.SH NAME
ignotum_strerror - get ignotum_status description
.SH SYNOPSIS
.B #include <ignotum.h>
.sp
.BI "const char *ignotum_strerror(ignotum_status " code);
.SH DESCRIPTION
return a description for ignotum_status type
.SH SEE ALSO
\fBignotum_status\fR(3)

