.TH ignotum_openmap 3 "07 May 2016" "Library" "libignotum man page"
.SH NAME
ignotum_openmap, ignotum_openmapstr - open /proc/[pid]/maps
.SH SYNOPSIS
.B #include <ignotum.h>
.sp
.BI "ignotum_status ignotum_openmap(pid_t " pid_number ", int *" fd_out);
.sp
.BI "ignotum_status ignotum_openmapstr(const char *" pid_str ", int *" fd_out);
.SH DESCRIPTION
open /proc/[\fIpid_number\fR]/maps on read-only mode, the file descriptor is returned on \fIfd_out\fR pointer
.SH RETURN VALUE
.B IGNOTUM_INVALID_PID_NUMBER
  the pid is minus than zero, or contain invalid chars like a, b, c, etc.

.B IGNOTUM_OPEN_MAP_FAILED
  failed to open /proc/[pid_number]/maps

.B IGNOTUM_SUCCESS
  no errors

.SH SEE ALSO

\fBignotum_sterror\fR(3), \fBignotum_status\fR(3), \fBread\fR(2)
