.TH ignotum_openmem 3 "07 May 2016" "Library" "libignotum man page"
.SH NAME
ignotum_openmem, ignotum_openmemstr - open /proc/[pid]/mem
.SH SYNOPSIS
.B #include <ignotum.h>
.sp
.BI "ignotum_status ignotum_openmem(pid_t " pid_number ", int *" fd_out ", int " mode ", int " attach_pid);
.sp
.BI "ignotum_status ignotum_openmemstr(const char *" pid_str ", int *" fd_out ", int " mode ", int " attach_pid);
.SH DESCRIPTION
open /proc/[\fIpid_number\fR]/mem using flags defined by \fImode\fR variable, if you want only read memory you can be use O_RDONLY,
if you also want write on memory use O_RDWR, for more info about open flags see \fBopen\fR(2). If
\fIattach_pid\fR is not equals zero the pid number will be attached using \fBptrace\fR(2), dont forget detach pid when you finish read/write memory

.SH RETURN VALUE
.B IGNOTUM_INVALID_PID_NUMBER
  the pid is minus than zero, or contain invalid chars like a, b, c, etc.

.B IGNOTUM_OPEN_MEM_FAILED
  failed to open /proc/[pid_number]/mem

.B IGNOTUM_SUCCESS
  no errors

.SH SEE ALSO

\fBignotum_sterror\fR(3), \fBignotum_status\fR(3), \fBptrace\fR(2), \fBopen\fR(2)
